# Generated by Django 5.1.6 on 2025-03-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_content_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_preview',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
